static const char *DefaultLanguageStringTable[SYS_UI_MSG_COUNT] = {
    "Quit program?",
    "Please wait...",
    "Selected device has insufficient space.",
    "Error accessing device.",
};

static const char *DefaultLanguageLabelStringTable[SYS_UI_LBL_COUNT] = {
    "OK",
    "Cancel",
    "Yes",
    "No",
    "Next",
    "Back",
    "Enabled",
    "Disabled",
    "Toggle option",
    "Select field",
    "Done",
    "Failed",
    "Dumping...",
    "Quit program",
    "Select device",
    "Warning",
    "Error",
    "Information",
    "Confirmation",
    "Please wait",
    "Memory card",
    "Slot 1",
    "Slot 2",
    "USB mass storage",
    "Return to main menu",
    "Dump system ROM",
    "System information",
    "Dumping ROMs",
    "Loading",
    "<Not detected>",
    "EE",
    "IOP",
    "GS",
    "SPU2",
    "Summary",
    "Mainboard",
    "ROM regions",
    "System ROM chips",
    "DEV9 interface",
    "USB interface",
    "i.Link interface",
    "Revision",
    "Implementation",
    "ID",
    "FPU revision",
    "FPU implementation",
    "ICache size",
    "DCache size",
    "RAM size",
    "SSBUS I/F revision",
    "AIF revision",
    "Model Name",
    "Mainboard model",
    "Chassis",
    "ROMVER",
    "ROMGEN",
    "Console ID",
    "i.Link ID",
    "Serial number",
    "Model ID",
    "SCE Model ID",
    "EMCS ID",
    "Machine type",
    "MECHACON revision",
    "MagicGate region",
    "System type",
    "M Renewal Date",
    "MPU board ID",
    "BoardInf",
    "rom0:",
    "rom1:",
    "rom2:",
    "erom:",
    "BOOT ROM",
    "DVD ROM",
    "EEPROM",
    "***No expansion device connected***",
    "SPEED revision",
    "SPEED capabilities",
    "MAC address",
    "PHY vendor",
    "PHY model",
    "PHY revision",
    "HC revision",
    "Ports",
    "Max speed",
    "Compliance",
    "Vendor ID",
    "Product ID",
    "bytes",
    "KB",
    "Mbit",
    "MB",
    "ADD0x010",
    "DVDVER",
    "PS1DRV",
    "ROM may be unclean",
};
